In [ ]:
mat = [[1, 2, 3, 4], [4, 5, 6, 7], [6, 7, 8, 9]]

for i in mat:
  for j in i:
    print(f"{j} ", end="")
  print("\n")

1 2 3 4 

4 5 6 7 

6 7 8 9 



In [ ]:
class Person:
  def __init__(self, name, age, gender):
    self.name = name
    self.age = age
    self.gender = gender
  
  def greet(self):
    print(f"Hello I'm {self.name}. I'm {self.age} years old")
  

person1 = Person("Bikash", 22, "Male");
person1.greet()

Hello I'm Bikash. I'm 22 years old


In [ ]:
import pandas as pd
import numpy as np


arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr + 1

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.mean(arr)

4.0

In [ ]:
np.std(arr)

2.0

In [ ]:
np.median(arr)

4.0

In [ ]:
np.max(arr)

7

In [ ]:
# Generates a 2D matrix of 9x9 with the values from 1(inclusive) to 10(exclusive)
npArr = np.random.randint(0, 256, size=(9,9))
npArr

array([[214, 137,  63,  14, 104,  25, 243, 180,   7],
       [144, 191, 142,  93,  71, 213, 169, 103, 229],
       [201,  51,  80, 135, 251,  63, 133, 104,  75],
       [202, 138,  48,  67,  95,  19, 114, 215,  44],
       [ 80, 168,  53, 175,  73, 106, 151, 123, 212],
       [ 28,  86, 250, 122,  52,  29,  69,  50, 117],
       [ 68,  72, 180,  57, 113,  74, 245,   9, 189],
       [ 20,  55,  49, 140, 223,  43, 128,  81,  42],
       [140,  13, 179, 107,   1, 247, 239, 153,  79]])

In [ ]:
np.mean(npArr)

114.4074074074074

In [ ]:
np.max(npArr)

251

In [ ]:
print(type(npArr))

<class 'numpy.ndarray'>


In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# slicing
arr[1:3]

array([2, 3])

In [ ]:
# negative indexing
arr[-1]

7

In [ ]:
# negative slicing - follows left-right pattern
arr[-7:-3]

array([1, 2, 3, 4])

In [1]:
print("googlecolab")

googlecolab
