In [1]:
# Install numpy

!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [8]:
# Include numpy library
import numpy as np
import random
arr = np.random.randint(1, 100, 10)
arr

array([59, 11, 15, 48, 89, 88, 34, 27, 33, 74])

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.ndim

1

In [21]:
ndArr = np.random.randint(0, 256, size=(50, 3))

In [22]:
ndArr

array([[154, 126,  44],
       [ 23, 139, 122],
       [ 65, 248, 214],
       [102, 221, 104],
       [251,  36, 129],
       [ 59,   3,  16],
       [ 30, 225, 209],
       [ 99, 169,  59],
       [ 45, 193, 148],
       [210, 132, 149],
       [ 94, 224,  71],
       [212, 228, 160],
       [ 88, 241, 163],
       [252,  66, 209],
       [145, 190,  64],
       [141, 161,  57],
       [173, 172, 109],
       [125, 177, 135],
       [ 51, 125, 175],
       [ 99, 122, 172],
       [ 79, 141, 222],
       [ 28,  96, 106],
       [216, 153, 224],
       [ 31,   5, 158],
       [ 34,  44, 152],
       [199,  87, 163],
       [ 53,  76,  59],
       [131, 239,  56],
       [200, 155, 104],
       [ 90,  30, 126],
       [ 77, 242,   6],
       [ 61, 192,  55],
       [194,  45,  72],
       [206,  94, 119],
       [ 46,  66,  81],
       [ 13,  97, 245],
       [ 13, 231, 213],
       [192,  45, 207],
       [ 39, 158, 188],
       [234,  95,  87],
       [250, 105, 255],
       [ 37,  55

In [27]:
colors = ["rgb"+str(tuple(rgb)) for rgb in ndArr]

In [28]:
colors

['rgb(154, 126, 44)',
 'rgb(23, 139, 122)',
 'rgb(65, 248, 214)',
 'rgb(102, 221, 104)',
 'rgb(251, 36, 129)',
 'rgb(59, 3, 16)',
 'rgb(30, 225, 209)',
 'rgb(99, 169, 59)',
 'rgb(45, 193, 148)',
 'rgb(210, 132, 149)',
 'rgb(94, 224, 71)',
 'rgb(212, 228, 160)',
 'rgb(88, 241, 163)',
 'rgb(252, 66, 209)',
 'rgb(145, 190, 64)',
 'rgb(141, 161, 57)',
 'rgb(173, 172, 109)',
 'rgb(125, 177, 135)',
 'rgb(51, 125, 175)',
 'rgb(99, 122, 172)',
 'rgb(79, 141, 222)',
 'rgb(28, 96, 106)',
 'rgb(216, 153, 224)',
 'rgb(31, 5, 158)',
 'rgb(34, 44, 152)',
 'rgb(199, 87, 163)',
 'rgb(53, 76, 59)',
 'rgb(131, 239, 56)',
 'rgb(200, 155, 104)',
 'rgb(90, 30, 126)',
 'rgb(77, 242, 6)',
 'rgb(61, 192, 55)',
 'rgb(194, 45, 72)',
 'rgb(206, 94, 119)',
 'rgb(46, 66, 81)',
 'rgb(13, 97, 245)',
 'rgb(13, 231, 213)',
 'rgb(192, 45, 207)',
 'rgb(39, 158, 188)',
 'rgb(234, 95, 87)',
 'rgb(250, 105, 255)',
 'rgb(37, 55, 138)',
 'rgb(105, 20, 144)',
 'rgb(188, 242, 205)',
 'rgb(204, 140, 51)',
 'rgb(152, 49, 101)',


In [41]:
# linspace

np.linspace(0,10,10) #(start, end, HowManyDivision)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [44]:
# arange
np.arange(13, 40, 4) #(start, end, incrementValue)

array([13, 17, 21, 25, 29, 33, 37])

In [31]:
np.arange(10.3, 30, 2.5)

array([10.3, 12.8, 15.3, 17.8, 20.3, 22.8, 25.3, 27.8])

In [47]:
arr

array([59, 11, 15, 48, 89, 88, 34, 27, 33, 74])

In [50]:
# Argmax - argument max and argument min

arr.argmax() # position of maximum value

4

In [51]:
arr.argmin() # position of minimum value

1

In [57]:
# Slicing and indexing 
arr[-1:]

array([74])

In [58]:
arr[-4:]

array([34, 27, 33, 74])

In [60]:
ndArr = np.random.randint(1, 100, size=(5, 3))

In [61]:
ndArr

array([[60,  3, 94],
       [53, 94, 38],
       [ 5,  8, 10],
       [83, 59, 67],
       [83,  4, 78]])

In [66]:
ndArr[0].argmax()

2

In [70]:
# Let's iterate through 2D array and find the index of maximum
# element in each of the array

maxValues = [num.argmax() for num in ndArr]

In [71]:
maxValues 

[2, 1, 2, 0, 0]

In [77]:
# Reshape
a = np.arange(0,12,1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
np.random.seed(242)
np.random.randint(1, 10, 10)

array([8, 3, 7, 2, 7, 5, 5, 4, 7, 4])

In [92]:
# random.seed can be useful when we need to generate same random numbers
# For ex: above cell and current cell generates same random numbers
np.random.seed(242)
np.random.randint(1, 10, 10)

array([8, 3, 7, 2, 7, 5, 5, 4, 7, 4])

In [98]:
# Log are very useful function in mathematics
# With the help of numpy we can easily find the log of any number 
# Just like this
np.log(10)

2.302585092994046

In [94]:
np.log(3)

1.0986122886681098

In [99]:
# Creating a random set of numbers and applying log function onto it
np.log10(np.random.randint(1, 10, 10))

array([0.60205999, 0.60205999, 0.60205999, 0.84509804, 0.60205999,
       0.69897   , 0.90308999, 0.69897   , 0.84509804, 0.95424251])

In [96]:
np.log(np.random.randint(1,10,10))

array([1.60943791, 0.69314718, 1.60943791, 1.60943791, 1.09861229,
       2.07944154, 1.94591015, 1.09861229, 1.09861229, 1.79175947])

#**Pandas in Python**





In [105]:
# Series and Dataframe in pandas

# Series - single column
# Dataframe - multiple column


import pandas as pd


a = np.arange(1, 20, 2)
a

s = pd.Series(a)
s

0     1
1     3
2     5
3     7
4     9
5    11
6    13
7    15
8    17
9    19
dtype: int64

In [112]:
# Slicing in Series 
s[-3:]

7    15
8    17
9    19
dtype: int64

In [113]:
# Indexing in Series
s[4]

9

In [114]:
# In Series, we can change the index values
s.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
s

a     1
b     3
c     5
d     7
e     9
f    11
g    13
h    15
i    17
j    19
dtype: int64

In [116]:
s['j']

19

In [117]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

In [119]:
s[1:9:2]

b     3
d     7
f    11
h    15
dtype: int64